[tool.poetry]
name = "arflow"
version = "0.3.0"
description = "ARFlow is a data-sharing layer that enables developer-friendly data streaming, storage, and visualization for augmented reality (AR) device data."
authors = ["Yiqin Zhao <yiqinzhao@outlook.com>"]
readme = "README.md"
packages = [{ include = "arflow" }, { include = "arflow_grpc" }]
license = "GPL-3.0"
homepage = "https://cake.wpi.edu/ARFlow/"
repository = "https://github.com/cake-lab/ARFlow"

[tool.poetry.urls]
"Paper" = "https://doi.org/10.1145/3638550.3643617"
"Video" = "https://youtu.be/mml8YrCgfTk"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
rerun-sdk = "^0.18.2"
grpcio = "^1.60.1"
grpcio-tools = "^1.60.1"
grpc-interceptor = "^0.15.4"
dracopy = "^1.4.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"             # Sync with `.github/ci.yml` if changed
pytest = "^8.3.2"
pytest-randomly = "^3.15.0"
pytest-cov = "^5.0.0"
pre-commit = "^3.8.0"
pyright = "^1.1.382"        # Sync with `.github/ci.yml` if changed
grpc-stubs = "^1.53.0.5"

[tool.poetry.group.docs.dependencies]
pdoc = "^14.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
arflow = "arflow._cli:main"

[tool.ruff]
# gRPC generated files
extend-exclude = ["examples", "arflow_grpc/**.py", "arflow_grpc/**.pyi"]

[tool.ruff.lint]
# https://github.com/astral-sh/ruff-vscode/blob/main/README.md#configuring-vs-code
extend-select = ["I"]
# Enable all `pydocstyle` rules, limiting to those that adhere to the
# Google convention via `convention = "google"`, below.
select = ["D", "T"]

# On top of the Google convention, disable `D417`, which requires
# documentation for every function parameter.
ignore = ["D417"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
typeCheckingMode = "strict"
exclude = ["examples", "arflow_grpc/**.py", "arflow_grpc/**.pyi"]

[tool.pytest.ini_options]
# coverage report for only `arflow` package with missing lines
addopts = "--cov arflow --cov-report term-missing"
